### ISSUE TITLE
没作用啊 空白的

### ISSUE THREAD

**Issue by moshuiNW** [xinyihl/LiteLoaderQQNT-RemoveSidebar#2]
[https://s1.imagehub.cc/images/2023/07/09/2023-07-09_195356.png](url)  这是什么情况 windows 9.9.0-14619 (64位)

**Comment by xinyihl** [comment]
选择左上角linux更新提交之前的版本应该可以，后面的提交没测试

**Comment by moshuiNW** [comment]
> 选择左上角linux更新提交之前的版本应该可以，后面的提交没测试

可以了,感谢。希望作者看到修改一下。

**Comment by xinyihl** [comment]
刚刚发的1.0应该没问题了，之前直接修改的代码没测试 [b454ede](https://github.com/xinyihl/LiteLoaderQQNT-RemoveSidebar/commit/b454edeaa91601fc170163c55fdb0ae24da42ed0)
