### ISSUE TITLE
配置页面空白

### ISSUE THREAD

**Issue by MillionZBW** [xinyihl/LiteLoaderQQNT-RemoveSidebar#3]
![image](https://github.com/xinyihl/LiteLoaderQQNT-RemoveSidebar/assets/23210456/590ebb8a-d459-43a5-8528-5e86cbcc4f9a)
![image](https://github.com/xinyihl/LiteLoaderQQNT-RemoveSidebar/assets/23210456/a1ccf004-14cd-44de-8d35-b731fd779bfa)

**Comment by xinyihl** [comment]
请尝试更新你的LiteLoaderQQNT至最新版本
注意不是Releases版本直接下载源码
