### ISSUE TITLE
控制台一直报错

### ISSUE THREAD

**Issue by EzraRT** [xinyihl/LiteLoaderQQNT-RemoveSidebar#4]
Macos下，`if (buttons.length > 2)` 处会一直报错
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at renderer.js:11:17
```

**Comment by xinyihl** [comment]
可以提供更多信息吗，我这边无法测试macos，可能会放弃支持

**Comment by EzraRT** [comment]
目前看来是buttons根据平台初始化未包含darwin的原因，测试了一下和linux的query方式相同，以下代码正常运行
https://github.com/xinyihl/LiteLoaderQQNT-RemoveSidebar/blob/b454edeaa91601fc170163c55fdb0ae24da42ed0/src/renderer.js#L8-L10
``` javascript
    if (LiteLoader.os.platform == "linux" || LiteLoader.os.platform == "darwin") {
        var buttons = document.querySelectorAll(".sidebar .nav-item");
    }
```

**Comment by xinyihl** [comment]
确实是我忘记了，你可以提个pr以解决该问题

**Comment by xinyihl** [comment]
fix at #5
