### ISSUE TITLE
devtools疯狂报错

### ISSUE THREAD

**Issue by qiyi71w** [xinyihl/LiteLoaderQQNT-RemoveSidebar#6]
LLQQNT重装成release版本（0.3.1）后devtools疯狂报错：
​ Uncaught ReferenceError: LiteLoader is not defined
    at /C:/Users/admin/Documents/LiteLoaderQQNT/plugins/LiteLoaderQQNT-RemoveSidebar/src/renderer.js:5:5
at file:///C:/Users/admin/Documents/LiteLoaderQQNT/plugins/LiteLoaderQQNT-RemoveSidebar/src/renderer.js:5:5 @ 

不知道是哪里出了问题（）

**Comment by xinyihl** [comment]
更新你的LiteLoaderQQNT至最新开发版本
