### ISSUE TITLE
多个QQ下会因为索引超出界限报错

### ISSUE THREAD

**Issue by Whuihuan** [xinyihl/LiteLoaderQQNT-RemoveSidebar#8]
比如说一个QQ的QQ游戏索引是5，但是另一个QQ没有QQ游戏，这个时候去找索引5的元素就会报错。而且多个QQ可能会因为手机上的配置不同，侧边栏数目、元素位置也不一样。看看有没有办法区分QQ

**Comment by xinyihl** [comment]
不会解决该问题，如果你有兴趣可以自行解决
